### ISSUE TITLE
No more response on personality switch

### ISSUE THREAD

**Issue by adrian5** [KJeff01/Cobra-AI#12]
The latest release(s) don't respond to AA/AB/AC etc. commands. It would be nice if they did.

Even better would be a command similar to Nullbot's `who` imo.

Running **WZ 4.0.0**

**Comment by KJeff01** [comment]
Hmm? It works for me. What are you doing exactly.

**Comment by adrian5** [comment]
When starting a new game it works again, no idea what happened.

Here's a [savegame](https://github.com/KJeff01/Cobra/files/6295796/savegame.zip) where the above commands yield no response, if you want to try. It's 8 player MizaMaze involving Cobra v1.50.

**Comment by adrian5** [comment]
Were you able to take a look? Do the chat commands work for you with that savegame?

Alternatively, try creating the following game:

Map: **MizaMaze (8P)**
Alliances: **Locked Teams**
Team A: **Player** + **2x Cobra (Hard)**
Team B: **5x Bonecrusher (Hard)**
I can still reproduce it that way.

**Comment by adrian5** [comment]
I figured out that it's likely WZ related, not Cobra in particular. [#1776](https://github.com/Warzone2100/warzone2100/issues/1766)
