### ISSUE TITLE
Give default feedback for commands

### ISSUE THREAD

**Issue by adrian5** [KJeff01/Cobra-AI#13]
Would be nice to get more live feedback on whether the AI has received/processed a command.

E.g.:

- Have `stats` return that there's no preferred target currently, instead of not replying at all
- Have `targetN` confirm that a player is now being targeted, or that the given `N` is an allied player (user made mistake)

**Comment by KJeff01** [comment]
Done in 6341c3ab6351675bcb11a87536208cffed229c61.
